# Use the official ROS humble Desktop image as a base (Ubuntu 20.04)
FROM osrf/ros:humble-desktop

# Set an environment variable for non-interactive installs
ENV DEBIAN_FRONTEND=noninteractive


# Update package lists and install additional packages (e.g., pip and other tools)
RUN apt-get update && apt-get install -y \
    python3-pip \
    iputils-ping \
    git \
    vim \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-rosidl-generator-dds-idl \
    && rm -rf /var/lib/apt/lists/*

# 2. 添加 agiros apt 源
COPY ./add-agiros-apt-source.sh /tmp/add-agiros-apt-source.sh
RUN chmod +x /tmp/add-agiros-apt-source.sh && /tmp/add-agiros-apt-source.sh && rm /tmp/add-agiros-apt-source.sh

# 3. 系统升级和 ROS/AGiROS 安装
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions python3-colcon-mixin python3-vcstool \
    agiros-loong-ros-base agiros-loong-control-msgs agiros-loong-ros2-control \
    agiros-loong-moveit agiros-loong-ros-ign agiros-loong-joint-state-publisher-gui \
    agiros-loong-kinematics-interface-kdl agiros-loong-rqt-joint-trajectory-controller \
    agiros-loong-rqt agiros-loong-rviz2 agiros-loong-rosbag2 ignition-fortress && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy your entire repository into the container
COPY . /app


# ===== GStreamer =====
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    libgirepository1.0-dev \
    libcairo2-dev \
    pkg-config \
    gir1.2-gtk-3.0 \
    libgstreamer1.0-dev \
    gir1.2-gstreamer-1.0 \
    && rm -rf /var/lib/apt/lists/*
# Install PyGObject using pip
RUN pip3 install PyGObject
# Run test file to check if PyGObject is installed correctly
WORKDIR /app
RUN python3 tests/test_gi.py
# ===== GStreamer =====


# ===== Installing unitree_sdk2 =====
# Build the Unitree SDK:
# Change to the unitree_sdk2 folder, make install.sh executable and run it,
# then create a build directory, run cmake and make.
WORKDIR /app/unitree_sdk2
RUN mkdir build && \
    cd build && \
    cmake .. && \
    sudo make install
# ===== Installing unitree_sdk2 =====


# ===== Installing unitree_ros2 =====
# Following https://github.com/unitreerobotics/unitree_ros2
# To get unitree_ros2 installed.
WORKDIR /app/unitree_ros2/cyclonedds_ws/src
RUN git clone https://github.com/ros2/rmw_cyclonedds -b humble && \
    git clone https://github.com/eclipse-cyclonedds/cyclonedds -b releases/0.10.x && \
    cd .. && \
    colcon build --packages-select cyclonedds
# Now, source the ROS2 environment and build the rest of the packages,
# skipping cyclone‑dds (which has already been built)
WORKDIR /app/unitree_ros2/cyclonedds_ws
RUN bash -c "source /opt/ros/humble/setup.bash && \
             pwd && \
             colcon build"
# Double check whether the build was successful
RUN ls -l /app/unitree_ros2/cyclonedds_ws
# ===== Installing unitree_ros2 =====


# Create a dedicated directory for your application code
WORKDIR /app

# Copy your docker_internal_setup.sh script into /app
COPY docker_internal_setup.sh .

# Make sure that pip points to pip3
RUN rm -f /usr/bin/pip && ln -sf /usr/bin/pip3 /usr/bin/pip

# Make sure that python points to python3
RUN rm -f /usr/bin/python && ln -sf /usr/bin/python3 /usr/bin/python

# Ensure that docker_internal_setup.sh is executable
RUN chmod +x docker_internal_setup.sh

# Set the entrypoint to start your application
ENTRYPOINT ["./docker_internal_setup.sh"]
CMD ["bash"]